### ISSUE TITLE
ratr0-converttiled: Errors

### ISSUE THREAD

**Issue by grovdata** [weiju/ratr0-utils#1]
```
Traceback (most recent call last):
  File "/home/user/.local/bin/ratr0-converttiled", line 34, in <module>
    args.palette24, args.force_depth, args.verbose)
  File "/home/user/.local/lib/python3.6/site-packages/ratr0/util/tiled.py", line 21, in convert_tiles
    colors = tiles.make_colors(im, force_depth, verbose)
AttributeError: module 'ratr0.util.tiles' has no attribute 'make_colors'
```

I tried using the `ratr0-converttiled` script but I find some errors, maybe it hasn't been updated after a refactoring or something (c370c187152f537c26ff2c549937d7dcc857c5c2 looks likely)?
Looks like it should use `png_utils.make_colors()` instead, but it is not only that that's the issue.

The line after (`tiles.write_tiles`) also have some different parameters such as `force_depth` and `create_mask`.

I first tried installing with pip but have also built from source.

**Comment by weiju** [comment]
Thanks for reporting this. I haven't used that tool in a while, so I did not realize it did not work. It should be fixed now and I uploaded to pypi.org so it can be upgraded with pip to version 0.1.5.
